### ISSUE TITLE
consul template functions ordering

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#13]
@grrtrr, that consul template functions, when doing {{subtract 9 2}} will give -7 instead of 7.
Do you know why?

To get 7 I have to use {{subtract 2 9}}, that looks really weird to me, and I really really want to reverse the order. What do you think?

**Comment by grrtrr** [comment]
You are correct - the template functions use [prefix notation](https://en.wikipedia.org/wiki/Polish_notation), so that `- A B` would result in `A - B`.

Looking at the [subtract function](https://github.com/hashicorp/consul-template/blob/de2ebf4/template_functions.go#L772), it does `a - b` in the body; but its arguments (`b, a interface{}`) are swapped.

I see you already added a commit to work around it. Would make sense to flag an issue over at the consul website; but as they are using this already, that might break their scripts (which express - A B as - B A :)

**Comment by suntong** [comment]
Glad you see the same way as well. 
Yeah, I figured that they did it for a reason, so I didn't bother report back. 
Good that we "borrowed" the code so that we will not be afraid that our changes break their things.
