### ISSUE TITLE
Visual modelling and code gen

### ISSUE THREAD

**Issue by gedw99** [go-easygen/easygen#16]
code gen and visual modelling have a bit of a coupled history.

I have not used Drakon but logn admired it for what its goals are.
there is now a golang generator in it
https://github.com/stepan-mitkin/drakon_editor/blob/master/generators/go.tcl

I am thinking about the idea of building a Drakon in golang with easygen driving it.
Its funny because in golang there is allot of tooling to AT parse golang and bring up a GUI for seeing the control flow and the usages etc. The single source of truth is the code itself, which definitly has its merits.
Then i think about all those large enterprise systems where you code gen from the DB first to make a DAL and then higher if you want. 

Well i knwo this is a bit of a rant of corts, but figured it was worth raising and get your own thoughts on this...

**Comment by suntong** [comment]
Thanks a lot for your interes @gedw99, 

To be honest, I've never herd of Drakon before, so I looked it up.  
If you are talking about [Drakon the algorithmic visual programming language](https://en.wikipedia.org/wiki/DRAKON), then honestly, that's something way beyond the scope of easygen. 

easygen is designed to be simple and straightforward, the most complicated template that I've designed so far is the two commandline auto gen, listed in the readme. Take a look at their sources. Anything beyond that would be too complicated. For example, even I have easygen, for managing the readme, I use [`emd`](https://github.com/mh-cbon/emd), for code gen from the DB, I rely on other tools. 

easygen is actually a thin layer wrapping on top of the Go default template engine. What you are talking about is a specialized tools, just like `emd`, or ROR, etc, which a whole different purpose. 

I'm sorry that I have to close it because it is way beyond the scope of easygen.
