### ISSUE TITLE
String manipulations in templates

### ISSUE THREAD

**Issue by romz-pl** [go-easygen/easygen#18]
Hi,

In my opinion it would be valuable to have (by default) the string manipulations in template.
In particular, I would like to call following code in template file:
```
{{range .Messages}}
{{$nn := .Name}}
{{$w = string.replace($nn, 'AAA', 'bbb')}}
{{end}}
```
As a result I would like to get string $w with all replaced string 'AAA' with 'bbb' in string $nn.
Could you suggest the solution for this problem?

Kind regards,
Zbigniew Romanowski
romz@wp.pl

**Comment by suntong** [comment]
Hi Zbigniew, 

I totally agree that the way to use existing function in Go template is really cumbersome in that you have to (re)define it before you can use it. However, because of this very reason, I don't want to define something that nobody uses, but rather, only includes those functions that are really useful to people. 

So to answer your request specifically, 

- First, luckily `string.replace` is so useful that is already define in easygen:
  https://github.com/go-easygen/easygen/blob/master/tf-strings.go#L24-L26
- Second, if you find any string manipulations functions missing but you need, please define them in [tf-strings.go](https://github.com/go-easygen/easygen/blob/master/tf-strings.go), and submit a PR. 
- Lastly, If you really want to define _all_ the string manipulations functions, then please use the plugable 
approach, e.g. https://github.com/go-easygen/easygen/blob/master/egVar/EgVar.go

Thx

**Comment by suntong** [comment]
Ahh, speaking too soon -- the https://github.com/go-easygen/easygen/blob/master/tf-strings.go#L24-L26 does not answer your request actually, when I took a second look -- it ties closely with `-rf string` & `-rt string`, so, hmm, ..., how would you want to proceed?

**Comment by suntong** [comment]
How to avoid name collision is another consideration I had, which resulted in that I didn't add all the string manipulations functions. For e.g., there is a `strings.Replace` and there need to be a `regexp.Replace` as well. And I don't know if `strings.replace` can be used as Go template function name or not. 

I.e., you've asked something that I don't have an answer yet, for now.

**Comment by romz-pl** [comment]
Hi suntong,

Thanks for seedy response.
Currently I need functions in string replacement, only.
At the begging it would be sufficient to have function replacing all sub-strings with another
with prototype
```
string_replace_all( str, a, b )
```
For example, for `str="AAxxAAyyAA"`, and `a="AA"`, and `b="BB"` the function `string_replace_all(str, a, b)` should return `BBxxBByy`.

Could you add this function into the easygen? I need this in my project.
What do you think?

**Comment by suntong** [comment]
Writing such a function is easy, but having a consistent naming convention that is good (and align with) the future is the hardest.  That's why I need to do some serious consideration and planning and don't want to rush it. 

That being said, I think I've finally have a good idea. But let me consult with @grrtrr first. Gerrit, please go through this thought trail and tell me if the following would be a good idea, 

- Instead of providing two functions, `strings.Replace` and `regexp.Replace`, I'm going to provide only the regexp one. 
- Instead of naming `regexp.Replacexxx`, I'll name it `regexpReplaceAllString`, thus avoiding the problem whether `regexp.Replace` can be used as Go template function or not. 

@romz-pl, 

The  `regexpReplaceAllString` will be as simple as:

```go
func regexpReplaceAllString(str, fromRexp, to string) {
    return regexp.MustCompile(fromRexp).
		ReplaceAllString(str, to)
}
```

If you can't wait, then please put that in yourself. Else, I'll find sometime to put it in, after reaching a consent with Gerrit first. 

Cheers

**Comment by grrtrr** [comment]
Thank you @suntong. From my own experiences, it would be useful to have such a string manipulation function available inside the template. 

Once in a while the template data contains things that are not interesting.

With regard to the command-line options for replacing strings (from -> to), would it be possible to express them in terms of a string template function (i.e. solve the conflict he other direction)?

**Comment by suntong** [comment]
Thanks @grrtrr, 

As long as you are not opposing it, I'll keep the `regexpReplaceAllString` naming convention. The main advantage is that they'll be self-explanatory, by their names. I.e., `regexpReplaceAllString` will correspond to `regexp.ReplaceAllString`, so even if we add a bunch of them, we don't need to spend time documenting each and every one of them. 

@romz-pl, I'll find sometime this weekend to put it/some in. 

As to the command-line options for replacing strings, let's continue the discussion at 
https://github.com/go-easygen/easygen/issues/19

**Comment by suntong** [comment]
I ended up adding a bunch of them: 

https://github.com/go-easygen/easygen/blob/8022ae39b5b2aa9001f159eeabaa82c7d010474d/t_strings_test.go#L35-L171

**Comment by grrtrr** [comment]
That looks great, I was looking for quite a few of these, and it was getting hard to work around.

Thank you for making easygen even more valuable!

**Comment by romz-pl** [comment]
That looks great!
